allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "${rootProject.projectDir}/local-repo" }
        maven {
            url 'https://jitpack.io'
            content {
                excludeGroup 'io.flutter'
            }
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
    configurations.configureEach {
        resolutionStrategy {
            force 'pl.droidsonroids.gif:android-gif-drawable:1.2.25'
        }
    }
    project.buildscript {
        configurations.configureEach {
            resolutionStrategy {
                force 'com.android.tools.build:gradle:8.6.0'
                force 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.1.0'
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
