android.useAndroidX=true
android.enableJetifier=true
android.enableR8.fullMode=true
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
systemProp.http.socketTimeout=120000
systemProp.http.connectionTimeout=120000
systemProp.https.socketTimeout=120000
systemProp.https.connectionTimeout=120000
