// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZM9MMaizcCmg_c-TDA9-WTeKvipdLFRA',
    appId: '1:202123276886:android:d8e774cb0b1f02474181f7',
    messagingSenderId: '202123276886',
    projectId: 'goride-a9d8f',
    databaseURL: 'https://goride-a9d8f-default-rtdb.firebaseio.com',
    storageBucket: 'goride-a9d8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX0jLAAEL6KWQeWE7hNVA7IL7kIBzzrFA',
    appId: '1:202123276886:ios:f1668f338d6f77be4181f7',
    messagingSenderId: '202123276886',
    projectId: 'goride-a9d8f',
    databaseURL: 'https://goride-a9d8f-default-rtdb.firebaseio.com',
    storageBucket: 'goride-a9d8f.firebasestorage.app',
    androidClientId:
        '202123276886-3eihnt78fpp7khqbb5ts9o7j160al802.apps.googleusercontent.com',
    iosClientId:
        '202123276886-47lq670ko4c61dmngfm8dpdqop0ebmsg.apps.googleusercontent.com',
    iosBundleId: 'com.goride.customer',
  );
}
